CREATE TABLE unit (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	symbol VARCHAR(255) NOT NULL, 
	UNIQUE INDEX UNIQ_DCBB0C535E237E06 (name), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE recipe_type (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	UNIQUE INDEX UNIQ_F3C50DF65E237E06 (name), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE material (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	UNIQUE INDEX UNIQ_7CBE75955E237E06 (name), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE grade (
	id INT AUTO_INCREMENT NOT NULL, 
	variant_id INT NOT NULL, 
	type_id INT NOT NULL, 
	unit_id INT DEFAULT NULL, 
	value INT DEFAULT NULL, 
	comment LONGTEXT DEFAULT NULL, 
	INDEX IDX_595AAE343B69A9AF (variant_id), 
	INDEX IDX_595AAE34C54C8C93 (type_id), 
	INDEX IDX_595AAE34F8BD700D (unit_id), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE recipe (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	UNIQUE INDEX UNIQ_DA88B1375E237E06 (name), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE variant (
	id INT AUTO_INCREMENT NOT NULL, 
	recipe_id INT DEFAULT NULL, 
	author VARCHAR(255) NOT NULL, 
	visible TINYINT(1) DEFAULT NULL, 
	main_variant TINYINT(1) DEFAULT NULL, 
	comment LONGTEXT DEFAULT NULL, 
	INDEX IDX_F143BFAD59D8A214 (recipe_id), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE variant_ingredient_quantity (
	variant_id INT NOT NULL, 
	ingredient_quantity_id INT NOT NULL, 
	INDEX IDX_B30819983B69A9AF (variant_id), 
	INDEX IDX_B3081998C6F88465 (ingredient_quantity_id), 
	PRIMARY KEY(variant_id, ingredient_quantity_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE variant_material_quantity (
	variant_id INT NOT NULL, 
	material_quantity_id INT NOT NULL, 
	INDEX IDX_A662F5633B69A9AF (variant_id), 
	INDEX IDX_A662F563DD9778F4 (material_quantity_id), 
	PRIMARY KEY(variant_id, material_quantity_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE variant_recipe_type (
	variant_id INT NOT NULL, 
	recipe_type_id INT NOT NULL, 
	INDEX IDX_7352EBC13B69A9AF (variant_id), 
	INDEX IDX_7352EBC189A882D3 (recipe_type_id), 
	PRIMARY KEY(variant_id, recipe_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE ingredientQuantity (
	id INT AUTO_INCREMENT NOT NULL, 
	ingredient_id INT NOT NULL, 
	variant_id INT NOT NULL, 
	unit_id INT NOT NULL, 
	quantity INT NOT NULL, 
	INDEX IDX_13FA9EDB933FE08C (ingredient_id), 
	INDEX IDX_13FA9EDB3B69A9AF (variant_id), 
	INDEX IDX_13FA9EDBF8BD700D (unit_id), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE step (
	id INT AUTO_INCREMENT NOT NULL, 
	variant_id INT DEFAULT NULL, 
	text VARCHAR(255) DEFAULT NULL, 
	picture LONGTEXT DEFAULT NULL, 
	INDEX IDX_43B9FE3C3B69A9AF (variant_id), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE materialQuantity (
	id INT AUTO_INCREMENT NOT NULL, 
	material_id INT NOT NULL, 
	variant_id INT NOT NULL, 
	quantity INT NOT NULL, 
	INDEX IDX_A3574EB2E308AC6F (material_id), 
	INDEX IDX_A3574EB23B69A9AF (variant_id), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE grade_type (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	UNIQUE INDEX UNIQ_22BC1A395E237E06 (name), 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
CREATE TABLE ingredient (
	id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
;
ALTER TABLE grade ADD CONSTRAINT FK_595AAE343B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id);
ALTER TABLE grade ADD CONSTRAINT FK_595AAE34C54C8C93 FOREIGN KEY (type_id) REFERENCES grade_type (id);
ALTER TABLE grade ADD CONSTRAINT FK_595AAE34F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id);
ALTER TABLE variant ADD CONSTRAINT FK_F143BFAD59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id);
ALTER TABLE variant_ingredient_quantity ADD CONSTRAINT FK_B30819983B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id) ON DELETE CASCADE;
ALTER TABLE variant_ingredient_quantity ADD CONSTRAINT FK_B3081998C6F88465 FOREIGN KEY (ingredient_quantity_id) REFERENCES ingredientQuantity (id) ON DELETE CASCADE;
ALTER TABLE variant_material_quantity ADD CONSTRAINT FK_A662F5633B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id) ON DELETE CASCADE;
ALTER TABLE variant_material_quantity ADD CONSTRAINT FK_A662F563DD9778F4 FOREIGN KEY (material_quantity_id) REFERENCES materialQuantity (id) ON DELETE CASCADE;
ALTER TABLE variant_recipe_type ADD CONSTRAINT FK_7352EBC13B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id) ON DELETE CASCADE;
ALTER TABLE variant_recipe_type ADD CONSTRAINT FK_7352EBC189A882D3 FOREIGN KEY (recipe_type_id) REFERENCES recipe_type (id) ON DELETE CASCADE;
ALTER TABLE ingredientQuantity ADD CONSTRAINT FK_13FA9EDB933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id);
ALTER TABLE ingredientQuantity ADD CONSTRAINT FK_13FA9EDB3B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id);
ALTER TABLE ingredientQuantity ADD CONSTRAINT FK_13FA9EDBF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id);
ALTER TABLE step ADD CONSTRAINT FK_43B9FE3C3B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id);
ALTER TABLE materialQuantity ADD CONSTRAINT FK_A3574EB2E308AC6F FOREIGN KEY (material_id) REFERENCES material (id);
ALTER TABLE materialQuantity ADD CONSTRAINT FK_A3574EB23B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id);
