INSERT INTO recipe_type (id, name) VALUES 
(1, Christopher)
(2, Adam)
(3, Victor)
(4, Tara)
(5, Michael)
(6, Richard)
(7, Jason)
(8, Jennifer)
(9, Tonya)
(10, Alan)
;
INSERT INTO grade (comment, type_id, unit_id, value, variant_id, id) VALUES 
(Itaque cupiditate laborum molestias. Veritatis reiciendis aperiam nostrum necessitatibus ipsa., 5, 7, 6, 10, 1)
(Commodi architecto assumenda distinctio. Quaerat delectus ratione assumenda aliquam non ex corporis. Esse est quasi possimus quia consequuntur., 9, 6, 1, 2, 2)
(Sint quo recusandae nesciunt., 5, 10, 2, 3, 3)
(Reprehenderit repudiandae veniam aut quia consequuntur deserunt tempore. Nostrum dicta ullam aperiam voluptas laudantium. Ab quod necessitatibus totam iste accusamus aspernatur., 4, 3, 6, 7, 4)
(Maiores nostrum dolorum adipisci deserunt quas. Aut suscipit placeat molestias vero ipsam. Nemo explicabo numquam aliquid deserunt suscipit consequuntur., 1, 8, 1, 10, 5)
(Cupiditate et suscipit dolores totam facere. Inventore fugit in doloribus assumenda modi iste. Reprehenderit accusamus laborum reprehenderit architecto nostrum. Ducimus ratione veniam quasi sapiente molestias., 9, 1, 9, 1, 6)
(Expedita reiciendis sequi optio sint fuga aut., 1, 7, 4, 5, 7)
(Cupiditate sapiente ipsa autem est consectetur., 4, 2, 2, 1, 8)
(Placeat reiciendis perspiciatis quia. Exercitationem cumque excepturi asperiores dolores iusto earum non., 3, 1, 10, 6, 9)
(Excepturi porro velit dolore ipsum eum. Laboriosam ipsa autem sequi cum deleniti. Quae quia non praesentium modi perspiciatis numquam voluptatibus., None, None, 6, None, 10)
;
INSERT INTO recipe (id, name) VALUES 
(1, Teresa Herrera)
(2, Sara Carpenter)
(3, Hailey Johnson)
(4, Jeffrey Sanchez)
(5, Shannon Leach)
(6, Kim Johnson)
(7, Elizabeth Fields DDS)
(8, Angela Cox)
(9, Brian Shelton)
(10, Tyler Adams)
;
INSERT INTO grade_type (id, name) VALUES 
(1, Nisi accusamus libero incidunt minus.)
(2, Numquam suscipit reiciendis hic fugiat odio numquam nesciunt.)
(3, Id aliquid saepe voluptates.)
(4, Blanditiis asperiores nulla similique sunt voluptatem.)
(5, Exercitationem ducimus quia officiis mollitia ipsum quas.)
(6, Accusantium accusantium voluptate dolor tenetur et quaerat eligendi.)
(7, Commodi ex hic officia excepturi dolore alias.)
(8, Reiciendis tempore illo consectetur ipsam.)
(9, Doloremque vero eaque non reprehenderit beatae.)
(10, Placeat voluptas maxime commodi quasi.)
;
INSERT INTO material (id, name) VALUES 
(1, Architecto omnis modi.)
(2, Animi facere temporibus aliquid.)
(3, Error dignissimos ipsum eligendi explicabo.)
(4, Eius cupiditate illo quo.)
(5, Molestiae hic perferendis illum quo voluptates quisquam.)
(6, Eligendi eum esse ea enim quam facilis.)
(7, Omnis architecto occaecati explicabo.)
(8, Aliquam in rem atque culpa pariatur veritatis.)
(9, Perferendis ipsa quidem aut cupiditate.)
(10, Fugit quod consectetur blanditiis tenetur corporis.)
;
INSERT INTO variant (comment, main_variant, author, visible, recipe_id, id) VALUES 
(Repellat et in rem quos possimus. Facilis cumque unde temporibus maiores., False, Voluptate qui non fuga voluptatum., False, 2, 1)
(Laborum amet mollitia laudantium quae. Quisquam voluptatem harum molestiae., True, Inventore ea ipsa eum suscipit numquam., False, 1, 2)
(Distinctio nulla occaecati. Nemo quas laborum odit., False, Commodi odit veniam nemo est., False, 2, 3)
(Amet eligendi libero aut. Incidunt pariatur saepe rem laborum unde quae., False, Maiores repellendus hic eligendi possimus laborum libero., False, 10, 4)
(Dolorum beatae quos facere vitae esse sint. Natus reiciendis minus soluta quam laudantium earum aut., True, Quae enim earum velit., True, 6, 5)
(Neque officia placeat non. Rerum rerum quam excepturi unde., False, Necessitatibus fuga neque illo voluptates neque dolor., True, 10, 6)
(Dicta adipisci maiores. Ratione repellendus consequatur molestiae pariatur modi quidem., True, Ut autem sit pariatur libero quia vero., False, 9, 7)
(In aspernatur necessitatibus ipsam cumque. Sequi eaque sint. Temporibus nostrum dicta consequuntur ab deleniti occaecati., True, Distinctio doloremque doloribus quae fugit., True, 10, 8)
(Magni error aliquid fugit corrupti. Maxime unde dolor quos. Laboriosam placeat praesentium ducimus neque., False, Optio mollitia eligendi repellendus., True, 7, 9)
(Quis tenetur tenetur facilis illum ut. Sint veritatis dolor et voluptates., False, Voluptatibus impedit aliquam sit quis aspernatur id., False, None, 10)
;
INSERT INTO ingredientQuantity (unit_id, ingredient_id, variant_id, id, quantity) VALUES 
(6, 6, 10, 1, 3)
(3, 6, 7, 2, 6)
(1, 10, 8, 3, 6)
(9, 9, 2, 4, 8)
(8, 2, 5, 5, 10)
(6, 2, 5, 6, 9)
(3, 9, 8, 7, 1)
(7, 3, 10, 8, 1)
(10, 4, 3, 9, 2)
(None, None, None, 10, 3)
;
INSERT INTO step (picture, text, id, variant_id) VALUES 
(Quaerat vitae at illo asperiores veritatis et. Nisi saepe doloremque voluptatum nobis tenetur. Laboriosam similique officia laboriosam ut ipsa autem., A atque maiores possimus sapiente explicabo id., 1, 10)
(Omnis delectus placeat earum. Quo alias eaque cum pariatur soluta. Magnam quam voluptate inventore tenetur molestiae., Rem molestias ab numquam ipsam quam quaerat., 2, 5)
(Fugiat facilis doloribus., Voluptatum minima neque perspiciatis aperiam facere., 3, 8)
(Harum id totam aliquid placeat. Voluptate dolor molestias officiis modi. Recusandae repellendus necessitatibus molestiae., Velit facere quod eos vero est quibusdam neque., 4, 3)
(Debitis alias officia modi pariatur facere vel. Rem repellendus optio corporis ducimus optio eveniet. Architecto velit similique sit consequatur veniam occaecati. Atque ipsum corrupti eos., Debitis facilis nam rem libero porro dolores., 5, 5)
(Dolorem amet aut deserunt., Beatae odio nesciunt modi., 6, 4)
(Assumenda asperiores a in. Consectetur quia vero. Doloremque voluptas fugiat soluta voluptas. Recusandae accusantium facere omnis., Asperiores iure dolores quo., 7, 9)
(Facere tempore debitis. Rem illum vero., Illum perspiciatis molestiae consectetur minima et., 8, 9)
(Id magni optio inventore natus soluta in. Voluptatem voluptas dolor ipsa reiciendis. In eveniet culpa minima molestias consequatur sunt., Eligendi veniam deleniti nihil sint., 9, 3)
(Commodi iste corrupti quaerat at cumque necessitatibus. Deserunt quo rerum magnam amet voluptate. Eos repellendus hic nisi vero debitis., Laudantium tenetur corporis vitae fuga., 10, None)
;
INSERT INTO materialQuantity (variant_id, id, material_id, quantity) VALUES 
(7, 1, 9, 5)
(5, 2, 4, 10)
(2, 3, 2, 2)
(6, 4, 5, 8)
(7, 5, 3, 7)
(10, 6, 3, 10)
(7, 7, 1, 1)
(10, 8, 5, 3)
(1, 9, 2, 9)
(None, 10, None, 10)
;
INSERT INTO variant_material_quantity (material_quantity_id, variant_id) VALUES 
(10, 3)
(1, 9)
(7, 5)
(10, 6)
(9, 7)
(10, 2)
(4, 8)
(4, 1)
(6, 4)
(None, None)
;
INSERT INTO variant_recipe_type (recipe_type_id, variant_id) VALUES 
(7, 2)
(10, 9)
(8, 10)
(4, 1)
(1, 4)
(3, 1)
(9, 7)
(6, 7)
(2, 5)
(None, None)
;
INSERT INTO variant_ingredient_quantity (ingredient_quantity_id, variant_id) VALUES 
(10, 8)
(7, 3)
(8, 2)
(2, 9)
(6, 5)
(5, 7)
(10, 10)
(4, 4)
(8, 1)
(None, None)
;
INSERT INTO unit (symbol, id, name) VALUES 
(Natus repellat vero nam eius nesciunt., 1, Tenetur dignissimos similique sunt non quia.)
(Nobis exercitationem aperiam quidem., 2, Voluptates excepturi commodi eius adipisci magni consequatur.)
(Architecto ut sequi perspiciatis aperiam corrupti ullam odit., 3, Soluta recusandae at facere.)
(Praesentium incidunt saepe cum odio eligendi., 4, Saepe neque hic ratione placeat dolorem sint velit.)
(Et repellendus corporis esse., 5, Beatae deserunt ducimus repudiandae soluta officiis.)
(Commodi fuga officia architecto et eos in., 6, Repudiandae ullam id quas nulla.)
(Alias molestiae quis ipsum dignissimos corrupti., 7, Corporis accusamus quos a quas itaque ipsum.)
(Voluptatem dignissimos reprehenderit magnam., 8, Blanditiis quod voluptas iure deleniti voluptates ducimus.)
(Excepturi quisquam harum aspernatur., 9, Unde debitis quaerat eveniet repellendus sunt laborum.)
(Ullam recusandae quo vero saepe ipsum unde., 10, Neque id vel praesentium.)
;
INSERT INTO ingredient (id, name) VALUES 
(1, Totam ipsum molestiae laudantium eum dignissimos reiciendis.)
(2, Saepe enim voluptates consectetur aperiam reiciendis quia veritatis.)
(3, Ullam dolorum eius deleniti quidem tenetur.)
(4, Nam tenetur nisi voluptates deleniti assumenda facere.)
(5, Quibusdam magnam cumque nihil doloremque temporibus.)
(6, Reiciendis cupiditate atque quaerat.)
(7, Dicta ipsum nam reprehenderit accusantium placeat consequatur.)
(8, Assumenda maiores magnam beatae ut impedit.)
(9, Exercitationem dolorem neque.)
(10, Est ad pariatur alias.)
;
