INSERT INTO recipe_type (id, name) VALUES 
(1, Neque et quod quia in dolore perspiciatis consequuntur.)
(2, Recusandae autem perspiciatis nihil praesentium voluptate.)
(3, Minus odio qui a placeat quis.)
(4, Architecto repudiandae magni sit neque.)
(5, Quasi eos repudiandae rerum amet repellat adipisci recusandae.)
(6, Natus asperiores nisi.)
(7, Ex dolorem aliquam accusantium.)
(8, Ipsa omnis nemo sunt voluptate tenetur.)
(9, In et assumenda modi ab enim accusantium.)
(10, Fuga alias atque nostrum minus.)
;
INSERT INTO grade (comment, type_id, unit_id, value, variant_id, id) VALUES 
(Dolorum asperiores aspernatur consectetur exercitationem. Perferendis placeat quia tempore consectetur necessitatibus accusamus exercitationem. Nobis eaque sapiente esse veritatis laborum. Animi optio aspernatur quam veniam., 4, 9, 10, 1, 1)
(Maiores aspernatur nobis. Debitis quam iusto necessitatibus ad quaerat hic., 6, 8, 8, 5, 2)
(Blanditiis dolorum magnam praesentium expedita iure accusantium. Enim a consectetur atque. Neque impedit et cupiditate expedita esse. Voluptas esse deserunt dignissimos rerum perferendis cumque., 6, 3, 5, 3, 3)
(Magnam amet porro corporis doloribus facilis numquam quasi. Ab consequuntur pariatur eum laborum quae numquam., 5, 1, 6, 4, 4)
(Aliquam placeat minus quam nihil. Ratione repudiandae optio. Incidunt sint facilis enim consequatur., 10, 4, 8, 4, 5)
(Sint enim libero. Eaque reiciendis natus rem ducimus fugiat quisquam. Consectetur consectetur repudiandae in., 3, 5, 3, 8, 6)
(Quam provident commodi sunt nesciunt odio nemo soluta., 7, 9, 5, 5, 7)
(Vel id perspiciatis. Magni numquam mollitia iusto reprehenderit. Accusantium sint aspernatur., 10, 7, 9, 6, 8)
(Natus saepe tempore perferendis vel., 3, 3, 7, 8, 9)
(Iusto fugiat sapiente. Odio veniam vero odit unde. Voluptas deserunt perferendis., None, None, 7, None, 10)
;
INSERT INTO recipe (id, name) VALUES 
(1, Iste molestias laborum quibusdam et accusantium quibusdam.)
(2, Quidem alias error necessitatibus.)
(3, Inventore minus eveniet quo ducimus.)
(4, Suscipit aperiam cum esse deserunt.)
(5, Illo iste nemo magnam illo.)
(6, Occaecati iusto dolor pariatur illum doloremque placeat.)
(7, Quo aperiam dolore magnam aspernatur.)
(8, Laborum similique blanditiis iure animi quidem eum.)
(9, Minus commodi saepe fugit.)
(10, Reiciendis atque quibusdam.)
;
INSERT INTO grade_type (id, name) VALUES 
(1, Porro rerum voluptatibus necessitatibus magni delectus.)
(2, Libero illum enim iure quisquam.)
(3, Error blanditiis deleniti aut ratione nulla.)
(4, Facilis dolores facere recusandae nobis repudiandae.)
(5, Voluptas quos occaecati voluptates unde.)
(6, Natus praesentium sed ipsam provident.)
(7, Sit repellat eos minus occaecati.)
(8, Sapiente doloremque doloribus ad dolores dolores.)
(9, Quas sit laboriosam minus.)
(10, Cumque odio itaque tenetur fugit omnis neque.)
;
INSERT INTO material (id, name) VALUES 
(1, Deserunt minima eos est porro omnis aperiam.)
(2, Enim quas facilis porro mollitia animi rerum aliquam.)
(3, Veniam deserunt excepturi unde vitae repudiandae.)
(4, Sed rerum dignissimos ad quis.)
(5, Modi enim libero tempora eos ea quia.)
(6, Enim illum aspernatur repudiandae alias dolorem nesciunt deserunt.)
(7, Repellendus in harum fugit tempora id.)
(8, Vel perferendis ad provident corporis perferendis molestiae voluptatem.)
(9, Ad cum tenetur nisi quos aliquid aspernatur culpa.)
(10, Quam ipsum impedit ex quas quae.)
;
INSERT INTO variant (comment, main_variant, author, visible, recipe_id, id) VALUES 
(Autem mollitia ipsam neque excepturi eaque perferendis. Consequatur praesentium eos aperiam explicabo iure impedit. Voluptate minus ullam porro alias unde iure., False, Consequuntur similique officia ut autem amet repudiandae voluptate., False, 3, 1)
(Id ratione quos aperiam tenetur aliquid dicta. Voluptates impedit perferendis fugit. Alias nobis officia at., True, Consequuntur autem delectus., False, 10, 2)
(Porro fuga quod et veniam dolor provident quis. Magnam natus nam ipsam earum. Est illum ad quo dolore fugiat reprehenderit. Quam dolor nisi quas veritatis quisquam aliquam., False, Modi excepturi dolorem sequi., False, 4, 3)
(Incidunt vel rem assumenda. Pariatur odio iusto nostrum tempora adipisci eaque., True, Accusamus vel numquam id dolorem officia., False, 8, 4)
(Qui nihil necessitatibus cumque. Sed voluptas ipsum necessitatibus quos quod aut., False, Deleniti doloribus enim veritatis necessitatibus dolores dolores., False, 7, 5)
(Id fugiat iste minima. Alias fuga ea. Fugiat fuga ipsa., True, Aliquam porro a velit consectetur., True, 6, 6)
(Magni quo perferendis dolores. Nemo eaque perferendis asperiores., True, Ea error modi commodi deleniti., True, 2, 7)
(Aliquam in adipisci provident. Dicta asperiores esse facilis laborum adipisci., False, Vero quas beatae accusantium., False, 2, 8)
(Molestiae placeat dolores occaecati animi harum accusantium. Quam atque possimus., False, Atque recusandae illum optio officiis., True, 2, 9)
(In ipsa doloremque voluptas natus. Soluta nihil temporibus distinctio nostrum pariatur et iusto., False, Alias earum quod deserunt libero., False, None, 10)
;
INSERT INTO ingredientQuantity (unit_id, ingredient_id, variant_id, id, quantity) VALUES 
(5, 10, 10, 1, 4)
(10, 1, 5, 2, 6)
(10, 10, 2, 3, 4)
(7, 7, 8, 4, 5)
(1, 8, 2, 5, 4)
(4, 6, 6, 6, 10)
(3, 10, 7, 7, 2)
(10, 1, 10, 8, 2)
(3, 5, 4, 9, 7)
(None, None, None, 10, 7)
;
INSERT INTO step (picture, text, id, variant_id) VALUES 
(A at suscipit eveniet unde enim. Laudantium maxime eveniet quos., Exercitationem iste fugit autem cupiditate sit., 1, 5)
(Sequi ullam laudantium vero dolore. Vero et veritatis sed. Animi officiis minima quaerat., Quasi distinctio dicta sint., 2, 4)
(Beatae voluptates nobis., Nihil hic nihil quas animi ex asperiores., 3, 3)
(Sequi rerum architecto soluta numquam quasi. Voluptas ut non. Soluta fugit provident placeat sapiente., Eum pariatur temporibus facere eum id occaecati., 4, 10)
(Culpa repudiandae est iusto commodi repudiandae explicabo maiores. Sint adipisci illo at. Optio veniam iste deleniti., Reprehenderit perferendis temporibus quibusdam itaque maxime., 5, 10)
(Beatae repellendus corrupti molestias occaecati id ratione., Error atque porro incidunt similique cupiditate., 6, 5)
(Totam consectetur eaque rerum quia fugit ad. Dolores iste officia aut. Accusamus facilis nesciunt tenetur repudiandae blanditiis., Tempore aliquam non doloremque corrupti ipsa accusamus., 7, 2)
(Molestias repellendus dolorum assumenda dolor. Nulla similique esse nostrum., Id a maxime eligendi., 8, 10)
(Illo nostrum hic debitis facere. Commodi sit laudantium hic. Cupiditate temporibus aut., Nulla voluptatibus tempore., 9, 1)
(Sunt delectus velit deleniti. Accusamus explicabo iure impedit. Quis labore nobis iste perspiciatis et expedita., Deleniti accusantium voluptatem nostrum dolores aut., 10, None)
;
INSERT INTO materialQuantity (variant_id, id, material_id, quantity) VALUES 
(10, 1, 3, 5)
(4, 2, 2, 6)
(9, 3, 7, 10)
(9, 4, 4, 1)
(4, 5, 8, 1)
(6, 6, 10, 3)
(5, 7, 2, 3)
(7, 8, 8, 8)
(10, 9, 9, 1)
(None, 10, None, 5)
;
INSERT INTO variant_material_quantity (material_quantity_id, variant_id) VALUES 
(8, 3)
(5, 8)
(1, 10)
(9, 6)
(1, 4)
(4, 7)
(10, 1)
(1, 5)
(4, 9)
(None, None)
;
INSERT INTO variant_recipe_type (recipe_type_id, variant_id) VALUES 
(8, 1)
(4, 3)
(10, 1)
(7, 1)
(1, 6)
(5, 1)
(3, 5)
(9, 6)
(2, 3)
(None, None)
;
INSERT INTO variant_ingredient_quantity (ingredient_quantity_id, variant_id) VALUES 
(7, 2)
(1, 9)
(2, 5)
(1, 8)
(3, 1)
(4, 3)
(2, 7)
(1, 6)
(9, 10)
(None, None)
;
INSERT INTO unit (symbol, id, name) VALUES 
(Magnam possimus illo voluptas reprehenderit molestias., 1, Ipsa voluptatem tenetur non quam rem inventore placeat.)
(Ea esse deleniti ipsum nihil quae., 2, Quas facere consequatur enim reiciendis.)
(Repudiandae commodi ex corporis esse., 3, Saepe nobis veritatis eos a itaque.)
(At nam aspernatur., 4, Quas repudiandae quibusdam dicta ipsum.)
(Beatae nisi quam molestiae alias magni animi aliquid., 5, Suscipit fugiat culpa ratione.)
(Suscipit repudiandae in animi ad., 6, Tempore atque voluptates tempore ipsum nisi fugiat velit.)
(Corporis consequuntur totam alias., 7, Ipsa velit eos laboriosam.)
(Minima recusandae ratione ad., 8, Quibusdam voluptate molestias perspiciatis dolore eligendi architecto totam.)
(Voluptatum dolor necessitatibus reiciendis id velit., 9, Expedita nulla explicabo architecto tempore.)
(Molestiae voluptatibus voluptatem culpa reprehenderit., 10, Nemo dolorum dolore vitae quae est similique tempore.)
;
INSERT INTO ingredient (id, name) VALUES 
(1, Perferendis ad quos reprehenderit at asperiores.)
(2, Incidunt earum est hic temporibus commodi facere.)
(3, Similique assumenda excepturi nulla incidunt labore.)
(4, Quis dolores culpa quis consequuntur debitis.)
(5, Laudantium quasi quibusdam.)
(6, Saepe culpa iusto dicta sequi voluptate dignissimos.)
(7, Molestias harum cupiditate aut necessitatibus ipsam animi neque.)
(8, Necessitatibus nobis asperiores deserunt possimus necessitatibus esse.)
(9, Et voluptate necessitatibus fugiat laboriosam optio.)
(10, Doloribus enim neque sint dolorum repellendus.)
;
